#!/bin/bash

SIMPLE_GO_CODE="// File: cmd/api/main.go\n package main \nimport \"fmt\" \nfunc main() { \nfmt.Println(\"Starting Server....\")\n}"

function debugger() {
  local message=$1
  local is_error_type=${2:-false}


  if [ "$is_error_type" = true ]
  then 
      echo -e "\033[0;31m[ERROR]\n$message"
  else
      echo -e "\033[0;34m$message test"
  fi

}


function create_directory_with_go_code(){
   local root_directory=$1
   local identifier=$2

   cd 
   cd $root_directory
   mkdir -p bin cmd/api internals migrations remote
   echo -e $SIMPLE_GO_CODE > cmd/api/main.go
   touch Makefile 

}


function create_go_api_structure() {
  local root_directory=$1
  local identifier=$2
  
  echo $root_directory

  debugger "I am about to create a directory structure named *$root_directory*.\nDo you want me to continue? [Yes/no]" 
  read user_authorization

  if [ $user_authorization = "Yes" ]
  then 
     debugger "Create directory structure..."
     create_directory_with_go_code $root_directory $identifier
  else
    debugger "Abort" true
  fi

}


function make-go-dir() {
  local root_directory=$1
  local identifier=$2

  if [ -z "$root_directory" ] || [ -z "$identifier" ]
  then
      debugger "You need to provide two arguments for this script to work.\nUsage: make-go-dir <root directory name> <identifier name>" true
  else
     create_go_api_structure $root_directory $identifier 
  fi


}
