#!/bin/bash


function debugger() {
  local message=$1
  local is_error_type=${2:-false}


  if [ "$is_error_type" = true ]
  then 
      echo -e "[ERROR]\n$message"
  else
      echo -e "$message"
  fi

}


function create_go_api_structure() {
  local root_directory=$1
  local identifier=$2
  
  echo $root_directory

  debugger "I am about to create a directory structure named *$root_directory*.\nDo you want me to continue? [Yes/no]" 
  read user_authorization

  if [ $user_authorization = "Yes" ]
  then 
     debugger "Create directory structure..."
  else
    debugger "Abort"
  fi

}


function make-go-dir() {
  local root_directory=$1
  local identifier=$2

  if [ -z "$root_directory" ] || [ -z "$identifier" ]
  then
      debugger "You need to provide two arguments for this script to work.\nUsage: make-go-dir <root directory name> <identifier name>" true
  else
     create_go_api_structure $root_directory $identifier 
  fi


}
