#!/bin/bash


function debugger() {
  local message=$1
  local is_error_type=${2:-false}


  if [ "$is_error_type" = true ]
  then 
      echo -e "[ERROR]\n$message"
  else
      echo -e "[DEBUG]\n$message"
  fi

}


function make-go-dir() {
  local top_level_directory=$1
  local identifier=$2
  local debugging_enabled=${3:-$DEFAULT_DEBUG_MODE}

  if [ -z "$top_level_directory" ] || [ -z "$identifier" ]
  then
      debugger "You need to provide two arguments for this script to work.\nUsage: make-go-dir <root directory name> <identifier name>" true
  else
      debugger "$top_level_directory ----  $identifier" 
  fi


}
